apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stores-ui 
  name: stores-ui
  namespace: stores
spec:
  replicas: 5
  selector:
    matchLabels:
      app: stores-ui
  template:
    metadata:
      labels:
        app: stores-ui
    spec:
      containers:
      - image: nginx
        name: nginx
