apiVersion: v1
kind: Namespace
metadata:
  name: stores
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stores-ui 
  name: stores-ui
  namespace: stores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stores-ui
  template:
    metadata:
      labels:
        app: stores-ui
    spec:
      containers:
      - image: nginx
        name: nginx
